from Tkinter import *
import accessory
root=Tk()
root.geometry('500x600') 
root.resizable(True, True)

	

frame_PORT_ARDUINO=Frame(root)
lable_ARDUINO = Label(frame_PORT_ARDUINO, bg = 'red', text= u'OPTION ARDUINO', font='arial 16')
lable_COM_PORT_ARDUINO = Label(frame_PORT_ARDUINO, text= u'COM PORT ARDUINO', font='arial 14')
text_COM_PORT=Text(frame_PORT_ARDUINO,height=1,width=2,font='Arial 14',wrap=WORD)
lable_START_PORT_ARDUINO = Label(frame_PORT_ARDUINO, text= u'START PORT ARDUINO', font='arial 14')
text_START_PORT=Text(frame_PORT_ARDUINO,height=1,width=2,font='Arial 14',wrap=WORD)
lable_FINISH_PORT_ARDUINO = Label(frame_PORT_ARDUINO, text= u'FINISH PORT ARDUINO', font='arial 14')
text_FINISH_PORT=Text(frame_PORT_ARDUINO,height=1,width=2,font='Arial 14',wrap=WORD)
lable_ARDUINO.grid(row=0,column=0)
lable_START_PORT_ARDUINO.grid(row=2,column=0)
text_START_PORT.grid(row=2,column=1)	
lable_FINISH_PORT_ARDUINO.grid(row=3,column=0)	
text_FINISH_PORT.grid(row=3,column=1)
lable_COM_PORT_ARDUINO.grid(row=1,column=0)
text_COM_PORT.grid(row=1,column=1)
frame_PORT_ARDUINO.grid(row=0,column=0)	


frame_Wite=Frame(root)
frame_Wite.grid(row=1,column=0)	


frame_COM_PORT_MIT=Frame(root)
lable_MIT = Label(frame_COM_PORT_MIT, bg = 'red', text= u'MIT', font='arial 16')
lable_COM_PORT_MIT = Label(frame_COM_PORT_MIT, text= u'COM PORT MIT', font='arial 14')
text_COM_PORT_MIT=Text(frame_COM_PORT_MIT,height=1,width=2,font='Arial 14',wrap=WORD)
lable_START_PORT_MIT = Label(frame_COM_PORT_MIT, text= u'START PORT MIT', font='arial 14')
text_START_PORT_MIT=Text(frame_COM_PORT_MIT,height=1,width=2,font='Arial 14',wrap=WORD)
lable_FINISH_PORT_MIT = Label(frame_COM_PORT_MIT, text= u'FINISH PORT MIT', font='arial 14')
text_FINISH_PORT_MIT=Text(frame_COM_PORT_MIT,height=1,width=2,font='Arial 14',wrap=WORD)
lable_MIT.grid(row=0,column=0)
lable_COM_PORT_MIT.grid(row=1,column=0)
text_COM_PORT_MIT.grid(row=1,column=1)
lable_START_PORT_MIT.grid(row=2,column=0)
text_START_PORT_MIT.grid(row=2,column=1)	
lable_FINISH_PORT_MIT.grid(row=3,column=0)	
text_FINISH_PORT_MIT.grid(row=3,column=1)
frame_COM_PORT_MIT.grid(row=0,column=1)	

frame_BUTTOM=Frame(root)
button_main_function=Button(frame_BUTTOM,text='main function',font='arial 14', width=20,height=1)
button_Temperature_reading=Button(frame_BUTTOM,text='Temperature reading',font='arial 14', width=20,height=1)
button_work_with_REZ=Button(frame_BUTTOM,text='work with REZ',font='arial 14', width=20,height=1)
button_work_with_ADDRESS=Button(frame_BUTTOM,text='work with ADDRESS',font='arial 14', width=20,height=1)
button_Coefficient_calculation=Button(frame_BUTTOM,text='Coefficient calculation',font='arial 14', width=20,height=1)
button_check_ADDRESS=Button(frame_BUTTOM,text='check ADDRESS',font='arial 14', width=20,height=1)
button_Check_REZ=Button(frame_BUTTOM,text='Check REZ',font='arial 14', width=20,height=1)
button_Write_OTP=Button(frame_BUTTOM,text='Write OTP',font='arial 14', width=20,height=1)
button_Form_file=Button(frame_BUTTOM,text='Form file',font='arial 14', width=20,height=1)
button_Test=Button(frame_BUTTOM,text='Test',font='arial 14', width=20,height=1, command=accessory.pause)
button_main_function.grid(row=0,column=0, sticky = 'w')
button_Temperature_reading.grid(row=1,column=0, sticky = 'w')
button_work_with_REZ.grid(row=2,column=0, sticky = 'w')
button_work_with_ADDRESS.grid(row=3,column=0, sticky = 'w')
button_Coefficient_calculation.grid(row=4,column=0, sticky = 'w')
button_check_ADDRESS.grid(row=5,column=0, sticky = 'w')
button_Check_REZ.grid(row=6,column=0, sticky = 'w')
button_Write_OTP.grid(row=7,column=0, sticky = 'w')
button_Form_file.grid(row=8,column=0, sticky = 'w')
button_Test.grid(row=9,column=0, sticky = 'w')
frame_BUTTOM.grid(row=2,column=0)	

frame_PANEL_WRITE_RIDER=Frame(root)
text_PANEL_WRITE_RIDER=Text(frame_PANEL_WRITE_RIDER,height=10,width=20,font='Arial 14',wrap=WORD)
text_PANEL_WRITE_RIDER.grid(row=0,column=0)
frame_PANEL_WRITE_RIDER.grid(row=2,column=1)	


root.mainloop()